"""reference tables

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 07:51:36.485572
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_day',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dow', sa.Integer(), nullable=False),
    sa.Column('dow_name', sa.String(length=3), nullable=False),
    sa.Column('is_weekend', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('is_payday', sa.Integer(), nullable=False),
    sa.Column('festival', sa.String(length=32), nullable=True),
    sa.Column('festival_ramp', sa.Float(), nullable=False),
    sa.Column('is_holiday', sa.Integer(), nullable=False),
    sa.Column('monsoon', sa.Integer(), nullable=False),
    sa.Column('is_operating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('district_travel',
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.Column('road_class', sa.String(length=16), nullable=False),
    sa.Column('free_flow_kmh', sa.Float(), nullable=False),
    sa.Column('depot_to_district_km', sa.Float(), nullable=False),
    sa.Column('depot_to_district_freeflow_min', sa.Float(), nullable=False),
    sa.Column('inter_stop_km', sa.Float(), nullable=False),
    sa.Column('inter_stop_freeflow_min', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('district')
    )
    op.create_table('outlet',
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.Column('dock_type', sa.String(length=16), nullable=False),
    sa.Column('parking_constraint', sa.String(length=16), nullable=False),
    sa.Column('mall_window', sa.String(length=16), nullable=True),
    sa.Column('window_open_time', sa.String(length=5), nullable=False),
    sa.Column('window_close_time', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('outlet_id')
    )
    op.create_table('road_condition',
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('disruption_index', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('district', 'date')
    )
    op.create_table('service_allowance',
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('dock_type', sa.String(length=16), nullable=False),
    sa.Column('service_allowance_min', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('brand', 'dock_type')
    )
    op.create_table('traffic_speed',
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('monsoon', sa.Integer(), nullable=False),
    sa.Column('speed_index', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('district', 'hour', 'monsoon')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('weight_cap_kg', sa.Float(), nullable=False),
    sa.Column('volume_cap_m3', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=16), nullable=False),
    sa.Column('km_per_l', sa.Float(), nullable=False),
    sa.Column('weekly_fuel_quota_l', sa.Float(), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('traffic_speed')
    op.drop_table('service_allowance')
    op.drop_table('road_condition')
    op.drop_table('outlet')
    op.drop_table('district_travel')
    op.drop_table('calendar_day')
    # ### end Alembic commands ###
