// Real excerpts from the repo for the code walkthrough (long lines wrapped; "..." marks elided code).
export type CodeCue = { text: string; hl: [number, number] }; // hl: inclusive 0-based line range to light up
export type CodeScene = { id: string; file: string; lang: "py" | "ts"; lines: string[]; cues: CodeCue[] };

export const CODE: CodeScene[] = [
  {
    id: "codepri",
    file: "packages/allocation/src/allocation/allocator.py",
    lang: "py",
    lines: [
      "def priority(o: Order) -> float:",
      '    """Higher is planned first."""',
      "    score = 0.0",
      "    if o.deferred_yesterday:",
      "        score += 1000  # never skip an outlet twice in a row",
      "    score += 20 * min(o.days_since_last_served, 14)",
      '    if o.brand == "Fresh" and o.temp_requirement == "chilled":',
      "        score += 120",
      "    ...",
      "    score += 100 * o.festival_ramp",
      "    return score",
      "",
      "",
      "def _scarcity(o: Order, v: Vehicle) -> tuple:",
      '    """Lower sorts first: use the least valuable vehicle that works."""',
      '    wasted_reefer = 1 if v.temp == "reefer" and o.temp_requirement != "chilled" else 0',
      '    wasted_van = 1 if v.type == "van" and o.parking_constraint != "van_only" else 0',
      "    return (wasted_reefer, wasted_van, v.volume_cap_m3, v.vehicle_id)",
    ],
    cues: [
      { text: "Priority decides who is planned first. An outlet skipped yesterday gets +1000, so it is never skipped twice.", hl: [3, 4] },
      { text: "Then days since last served, chilled Fresh orders, tight windows and the festival ramp.", hl: [5, 9] },
      { text: "Placement picks the least valuable vehicle that works: reefers and vans stay free for orders that need them.", hl: [13, 17] },
    ],
  },
  {
    id: "codefit",
    file: "packages/allocation/src/allocation/allocator.py",
    lang: "py",
    lines: [
      "def fits(self, trip: Trip, o: Order) -> DeferralReason | None:",
      '    """None if `o` can join `trip`, else the reason it cannot."""',
      "    v = self.vehicles[trip.vehicle_id]",
      "    if sum(x.weight_kg for x in trip.orders) + o.weight_kg > v.weight_cap_kg:",
      "        return DeferralReason.CAPACITY_WEIGHT",
      "    if sum(x.volume_m3 for x in trip.orders) + o.volume_m3 > v.volume_cap_m3:",
      "        return DeferralReason.CAPACITY_VOLUME",
      "    ...  # daily time budget, using trip_minutes(grown, self.std)",
      "    if not self._fuel_ok(v, trip, grown):",
      "        return DeferralReason.FUEL_QUOTA",
      "    return None",
      "",
      "",
      "# trip_time.py",
      "MAX_TRIPS_PER_VEHICLE = 2",
      'BUDGET_MIN = {"Fresh": 270, "Style+Tech": 480}',
    ],
    cues: [
      { text: "Before an order joins a trip, fits() checks weight and volume against the vehicle.", hl: [3, 6] },
      { text: "It also checks the daily time budget and the weekly fuel quota.", hl: [7, 9] },
      { text: "When something fails, the order gets a reason code the store can read, not a silent drop.", hl: [4, 4] },
      { text: "Trip time follows the booklet's formula, with 270 and 480 minute budgets and two trips per vehicle.", hl: [13, 15] },
    ],
  },
  {
    id: "codesync",
    file: "services/api/app/routers/driver.py",
    lang: "py",
    lines: [
      '@router.post("/sync")',
      "def sync(body: SyncBody, user: User = Driver, db: Session = Depends(get_db)) -> dict:",
      '    """Idempotent upload of the phone\'s outbox, oldest device timestamp first."""',
      "    results = []",
      "    for ev in sorted(body.events, key=lambda e: e.device_ts):",
      "        results.append(_apply(db, user, ev))",
      "    ...",
      "",
      "",
      "def _apply(db: Session, user: User, ev: EventIn) -> dict:",
      "    if db.scalar(select(DeliveryEvent).where(DeliveryEvent.client_uuid == ev.client_uuid)):",
      '        return {**res, "status": "duplicate"}',
      "    trip = db.get(Trip, ev.trip_id)",
      "    if trip is None or trip.vehicle_id != user.vehicle_id:",
      '        return {**res, "status": "rejected", "message": "This trip is not yours"}',
      "    ...",
      "        if stop.removed:",
      '            c = Conflict(stop_id=stop.id, kind="reassigned")',
    ],
    cues: [
      { text: "The phone uploads its outbox in the order things happened on the device.", hl: [2, 5] },
      { text: "Every event has a client UUID. A repeat is recognised and reported as a duplicate, never applied twice.", hl: [10, 11] },
      { text: "A driver can only write to their own vehicle's trip.", hl: [12, 14] },
      { text: "If dispatch moved a stop while the driver was offline, it becomes a conflict to review, not an overwrite.", hl: [16, 17] },
    ],
  },
  {
    id: "codeguard",
    file: "services/api/app/deps.py",
    lang: "py",
    lines: [
      "def require(*roles: str):",
      "    def dep(user: User = Depends(current_user)) -> User:",
      "        if user.role not in roles:",
      "            raise HTTPException(",
      "                status.HTTP_403_FORBIDDEN, f\"This is for the {' / '.join(roles)} role\"",
      "            )",
      "        return user",
      "",
      "    return dep",
      "",
      "",
      "# one line per router",
      'Dispatcher = Depends(require("dispatcher"))   # routers/dispatch.py',
      'Loader = Depends(require("loader"))           # routers/loader.py',
      'Driver = Depends(require("driver"))           # routers/driver.py',
    ],
    cues: [
      { text: "Every router declares its role in one line. A dependency reads the signed session token.", hl: [11, 14] },
      { text: "Wrong role? A 403 comes back before any handler code runs.", hl: [2, 5] },
      { text: "Passwords and loader PINs are PBKDF2-hashed, and a store manager only ever sees their own outlet.", hl: [0, 8] },
    ],
  },
];
